= VIHAL Pin / Pad configuration + GPIO control

[source,c++]
----
#include "hwpins.h"

class THwPinCtrl
{
  bool PinSetup(int aportnum, int apinnum, unsigned flags);
  void GpioSet(int aportnum, int apinnum, int value);
};

class TGpioPort
{
  void Assign(int aportnum);
  void Set(unsigned value);
};

class TGpioPin
{
  TGpioPin(int aportnum, int apinnum, bool ainvert);  // normal constructor, calls Assign()
  TGpioPin(); // empty constructor, Assign() must be called later

  void Assign(int aportnum, int apinnum, bool ainvert);
  bool Assigned();
  bool Setup(unsigned flags);

  void Set0();
  void Set1();
  void SetTo(unsigned value);
  void Toggle();

  unsigned char Value();
  unsigned char OutValue();
  void SwitchDirection(int adirection);
};
----

[options="header"]
|=======================
|Pin Flag         | Description

|PINCFG_INPUT     | Specifies pin direction as input
|PINCFG_OUTPUT    | Specifies pin direction as output
|PINCFG_OPENDRAIN | Sets Open-Drain mode (allows multiple driver with a pull-up resistor)
|PINCFG_PULLUP    | Activates the integrated weak pull-up resistor
|PINCFG_PULLDOWN  | Activates the integrated weak pull-down resistor
|PINCFG_ANALOGUE  | Hints for analogue usage of the pin. (Usually turns out the Schmitt trigger)

|PINCFG_DRIVE_NORMAL +
PINCFG_DRIVE_WEAK +
PINCFG_DRIVE_MEDIUM +
PINCFG_DRIVE_STRONG | Set the output driving strength. The default is "NORMAL", which is usually not the maximum. The supported options are depends on the actual MCU.

|PINCFG_SPEED_SLOW + 
PINCFG_SPEED_MEDIUM +
PINCFG_SPEED_FAST   | Sets the speed limitiation on the pins. High speed pins might gerate interferences / disturbances. Default is "MEDIUM". The supported options are depends on the actual MCU.

|PINCFG_GPIO_INVERT | GPIO inversion at hardware level. Only a few MCU supports this.
| | Initialize the output pin to level "1". This is useful to avoid short unwanted pulses at the initialziation
|PINCFG_GPIO_INIT_0 | Initialize the output pin to level "0". This is useful to avoid short unwanted pulses at the initialziation

|PINCFG_AF_[0-15], +
PINCFG_AF_[A-P]     | Selects the alternate function (special function) for the pin. The alternate functions / special functions are usually descriped in the microcontroller datasheet or reference manual. Some MCU (like ATSAM) use letters in the pin function table, therefore the equivalent definitions also provided
|=======================

= Examples
== GPIO
[source,c++]
----
// Usual GPIO output scenario
//----------------------------
TGpioPin  pin_led1(PORTNUM_C, 13, true);  

pin_led1.Setup(PINCFG_OUTPUT | PINCFG_GPIO_INIT_1); 

// If the pins assigned later
//---------------------------
TGpioPin  pin_led[MAX_LEDS] = { TGpioPin(), TGpioPin(), TGpioPin(), TGpioPin() };  

pin_led[0].Assign(PORTNUM_C, 13, true);
pin_led[0].Setup(PINCFG_OUTPUT | PINCFG_GPIO_INIT_1); 

----
== Special Functions
[source,c++]
----
hwpinctrl.PinSetup(PORTNUM_A,  9,  PINCFG_OUTPUT | PINCFG_AF_1);  // USART1_TX (STM32)
hwpinctrl.PinSetup(0, 14, PINCFG_OUTPUT | PINCFG_AF_1); // SPI1_SCK (RP2040)
hwpinctrl.PinSetup(PORTNUM_A, 0, PINCFG_INPUT | PINCFG_ANALOGUE); // analogue input (STM32)
hwpinctrl.PinSetup(0, 27, PINCFG_INPUT | PINCFG_ANALOGUE); // ADC1 (RP2040)
hwpinctrl.PinSetup(PORTNUM_A, 17, PINCFG_AF_A);  // TWI0_SDA (TWD) (ATSAM3X)
hwpinctrl.PinSetup(PORTNUM_B,  8, PINCFG_AF_D | PINCFG_PULLUP); // SERCOM4/PAD0 = SDA (ATSAME51)

----
