= VIHAL Pin / Pad configuration + GPIO control

[source,c++]
----
#include "hwpins.h"

class THwPinCtrl
{
  bool PinSetup(int aportnum, int apinnum, unsigned flags);
  void GpioSet(int aportnum, int apinnum, int value);
};

class TGpioPort
{
  void Assign(int aportnum);
  void Set(unsigned value);
};

class TGpioPin
{
  TGpioPin(int aportnum, int apinnum, bool ainvert);  // normal constructor, calls Assign()
  TGpioPin(); // empty constructor, Assign() must be called later

  void Assign(int aportnum, int apinnum, bool ainvert);
  bool Assigned();
  bool Setup(unsigned flags);

  void Set0();
  void Set1();
  void SetTo(unsigned value);
  void Toggle();

  unsigned char Value();
  unsigned char OutValue();
  void SwitchDirection(int adirection);
};
----

[options="header"]
|=======================
|Pin Flag         | Description

|PINCFG_INPUT     | Specifies pin direction as input
|PINCFG_OUTPUT    | Specifies pin direction as output
|PINCFG_OPENDRAIN | Sets Open-Drain mode (allows multiple driver with a pull-up resistor)
|PINCFG_PULLUP    | Activates the integrated weak pull-up resistor
|PINCFG_PULLDOWN  | Activates the integrated weak pull-down resistor
|PINCFG_ANALOGUE  | Hints for analogue usage of the pin. (Usually turns out the Schmitt trigger)

|PINCFG_GPIO_INVERT | GPIO inversion at hardware level. Not all MCU supports it.
|PINCFG_GPIO_INIT_1 | Initialize the output pin to level "1". This is useful to avoid short unwanted pulses at the initialziation
|PINCFG_GPIO_INIT_0 | Initialize the output pin to level "0". This is useful to avoid short unwanted pulses at the initialziation

|PINCFG_AF_[0-15], +
PINCFG_AF_[A-P]     | Selects the alternate function (special function) for the pin. The alternate functions / special functions are usually descriped in the microcontroller datasheet or reference manual. Some MCU (like ATSAM) use letters in the pin function table, therefore the equivalent definitions also provided
|=======================

= Examples
