= VIHAL Pin / Pad configuration

[source,c++]
----
#include "hwpins.h"
----

The microcontrollers usually provide multiple functions on some of their pins (also called pads). 
Therefore the pin configuration is required before using the MCU pins.

The VIHAL provides the "hwpinctrl" object for the setup:
[source,c++]
----
THwPinCtrl  hwpinctrl;
----

The actual pin/pad setup is carried out by these methods:

[source,c++]
----
bool THwPinCtrl::PinSetup(int aportnum, int apinnum, unsigned flags);  // most common case
bool THwPinCtrl::PadSetup(int apadnum, int afuncnum, unsigned flags);  // special MCU case
bool TGpioPin::Setup(unsigned flags);  // for already assigned GPIO pins
----

aportnum, apinnum::
  Selects the pin you want to set-up. The pins are organized usually in ports, where one port might contain 16 or 32 pins.
  Some MCUs use letters for the ports, therefore the PORTNUM_[A-K] helper identifiers also defined.
  (If the MCU does not have multiple ports, then call the PinSetup() with aportnum=0.)

flags::
  A combination of predefined flags, see the "Pin Flag" table below

[options="header"]
|=======================
|Pin Flag         | Description

|PINCFG_INPUT     | Specifies pin direction as input
|PINCFG_OUTPUT    | Specifies pin direction as output
|PINCFG_OPENDRAIN | Sets Open-Drain mode (allows multiple driver with a pull-up resistor)
|PINCFG_PULLUP    | Activates the integrated weak pull-up resistor
|PINCFG_PULLDOWN  | Activates the integrated weak pull-down resistor
|PINCFG_ANALOGUE  | Hints for analogue usage of the pin. (Usually turns out the Schmitt trigger)

|PINCFG_DRIVE_NORMAL +
PINCFG_DRIVE_WEAK +
PINCFG_DRIVE_MEDIUM +
PINCFG_DRIVE_STRONG | Set the output driving strength. The default is "NORMAL", which is usually not the maximum. The supported options are depends on the actual MCU.

|PINCFG_SPEED_SLOW + 
PINCFG_SPEED_MEDIUM +
PINCFG_SPEED_FAST   | Sets the speed limitiation on the pins. High speed pins might gerate interferences / disturbances. Default is "MEDIUM". The supported options are depends on the actual MCU.

|PINCFG_GPIO_INVERT | GPIO inversion at hardware level. Only a few MCU supports this.
| | Initialize the output pin to level "1". This is useful to avoid short unwanted pulses at the initialziation
|PINCFG_GPIO_INIT_0 | Initialize the output pin to level "0". This is useful to avoid short unwanted pulses at the initialziation

|PINCFG_AF_[0-15], +
PINCFG_AF_[A-P]     | Selects the alternate function (special function) for the pin. The alternate functions / special functions are usually descriped in the microcontroller datasheet or reference manual. Some MCU (like ATSAM) use letters in the pin function table, therefore the equivalent definitions also provided
|=======================

= Examples

[source,c++]
----
hwpinctrl.PinSetup(PORTNUM_A,  9,  PINCFG_OUTPUT | PINCFG_AF_1);  // USART1_TX (STM32)
hwpinctrl.PinSetup(0, 14, PINCFG_OUTPUT | PINCFG_AF_1); // SPI1_SCK (RP2040)
hwpinctrl.PinSetup(PORTNUM_A, 0, PINCFG_INPUT | PINCFG_ANALOGUE); // analogue input (STM32)
hwpinctrl.PinSetup(0, 27, PINCFG_INPUT | PINCFG_ANALOGUE); // ADC1 (RP2040)
hwpinctrl.PinSetup(PORTNUM_A, 17, PINCFG_AF_A);  // TWI0_SDA (TWD) (ATSAM3X)
hwpinctrl.PinSetup(PORTNUM_B,  8, PINCFG_AF_D | PINCFG_PULLUP); // SERCOM4/PAD0 = SDA (ATSAME51)

// Some MCUs have special PAD setup functions:
hwpinctrl.PadSetup(4, FUNC_UART3_RX, PINCFG_INPUT);   // UART3_RX (Kendryte K210)
hwpinctrl.PadSetup(5, FUNC_UART3_TX, PINCFG_OUTPUT);  // UART3_TX (Kendryte K210)

// GPIO Setup
TGpioPin  pin_led1(PORTNUM_C, 13, true);  
pin_led1.Setup(PINCFG_OUTPUT | PINCFG_GPIO_INIT_1); 
----
